### ISSUE TITLE
Input channels

### ISSUE THREAD

**Issue by Viresh-R** [szagoruyko/imagenet-validation.torch#3]
Hi Sergey,
I want to finetune the alexnet_torch.t7 model(https://gist.github.com/szagoruyko/dd032c529048492630fc) on a different dataset. Are the input channels to the net RGB, or BGR ? Also, which channels do the mean and std values stored in net.transform() correspond to ?
Thanks
{
  mean :
    {
      1 : 0.48462227599918
      2 : 0.45624044862054
      3 : 0.40588363755159
    }
  std :
    {
      1 : 0.22889466674951
      2 : 0.22446679341259
      3 : 0.22495548344775
    }
}

**Comment by szagoruyko** [comment]
it's RGB as torch/image loads RGB. mean values correspond to RGB

**Comment by Viresh-R** [comment]
Thanks ! Closing the issue.
